name: page push
on: [push]
jobs:
  build_and_deploy:
    name: build elm and push to pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: compile from elm
        uses: jorelali/setup-elm@v3
        with:
          elm-version: 0.19.1
      - run: elm make --optimize --output=public/index.html src/RotatingCan.elm 
      - name: copy textures
        run: cp -a textures public
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: public
